### ISSUE TITLE
(requesting new features) i want to query all test cases such as select, where 

### ISSUE THREAD

**Issue by zxcviqekjkasdfl9** [r22n/casey#1]
i want new features of casey which queries all test cases such as select, where, and so on...
for example: querying test cases for all test cases by conditions combinations like below;
java -jar casey.jar -c allcondition.csv -t alltestcase.csv -q "select * where button-del=='OK' and checkfor=='showcaution'"

i except that the casey shows test cases have button-del is OK and checkfor is showcaution only

**Comment by r22n** [comment]
featuring overview:
1. query body: casey reads the query consisted of phrases.
<instruction token 0> <argument token 00> <argument token 01> ... 
<instruction token 1> <argument token 10> <argument token 11> ...
all tokens must have white space between its at least 1 count.

2. instructions: processing for all test case rows.
select <col header name token 0>, <col header name token 1> ...
casey picks up specified column and makes test cases table consisted of its column only.

where <expression>
casey skips all test cases which has not hit by <expression> condition.
<expression> can use col header name as variable name.

<expression>
( <col header name token 0> <compare token> <col header name token 1> )

<compare token>
== equals
!= not equals
% left variable contains right variable as substring
< greater than
> less than
<= greater equal than
>= less equal than

**Comment by r22n** [comment]
i have added new features of select and filter queries in v2.0.
java -jar casey.jar -c todo -t todo -f "{'header name as variable'}<='2'" -s HeaderName0 HeaderName1 and so on...

please read dat/helpall !
