### ISSUE TITLE
casey shows difficult error message while specifying the filter query which includes empty token 

### ISSUE THREAD

**Issue by zxcviqekjkasdfl9** [r22n/casey#3]
please show the error message what easy to read to me such as:
"empty token occurred in left hand of <."

casey shows difficult error message in below case.
- error message:
"failed to prepare test case: mal format occurred while parsing xxx:
tokens contains null"
- filter query:
-f "{'hoge'}<'" 
-f "'"

**Comment by r22n** [comment]
Ok merged
